// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_CJuTtn63GI8i-KacjBVZ7IulkqQJYiI',
    appId: '1:416744689820:web:158c64b42963bb8c9a9d59',
    messagingSenderId: '416744689820',
    projectId: 'allright01',
    authDomain: 'allright01.firebaseapp.com',
    storageBucket: 'allright01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCqasJsWAqfzIN2lssnx_cZmr-j5QEiCY',
    appId: '1:416744689820:android:3dd0fbcbab242e0d9a9d59',
    messagingSenderId: '416744689820',
    projectId: 'allright01',
    storageBucket: 'allright01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7fs4y1le9PM1Nwy6b69dUBQU3l7_2bpw',
    appId: '1:416744689820:ios:6d227ca8397873189a9d59',
    messagingSenderId: '416744689820',
    projectId: 'allright01',
    storageBucket: 'allright01.appspot.com',
    iosClientId:
        '416744689820-5jrcmsafgad29l262o4inc1iujtq08pt.apps.googleusercontent.com',
    iosBundleId: 'com.egba.org.allright',
  );
}
